services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - app-network
    env_file:
      - .env
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp

networks:
  app-network:
    driver: bridge
